services:
    output_filter:
        class: Ihsan\Compressor\Bridge\Symfony\HtmlCompressorOutputFilter
        arguments:
            - @kernel
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    css_filter:
        class: Ihsan\Compressor\Bridge\Symfony\AsseticCssFilter
        tags:
           - { name: assetic.filter, alias: css_compressor }

    ihsan.simple_admin.crud_annotation_reader:
        class: Ihsan\SimpleAdminBundle\EventListener\AnnotationListener
        arguments:
            - @annotation_reader
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }

    ihsan.simple_admin.user_controller_dependency_pass:
        class: Ihsan\SimpleAdminBundle\EventListener\UserControllerDependencyPassListener
        arguments:
            - @service_container
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }

    ihsan.simple_admin.twig_global_variable_pass:
        class: Ihsan\SimpleAdminBundle\EventListener\TwigGlobaVariablePassListener
        arguments:
            - @service_container
        tags:
            - { name: "kernel.event_listener", event: "kernel.request", method: "onKernelRequest" }

    ihsan.simple_admin.menu:
        class: Ihsan\SimpleAdminBundle\Menu\Builder
        arguments:
            - @router

    ihsan.simple_admin.main_menu:
        class: Knp\Menu\MenuItem
        factory_service: app.menu
        factory_method: mainMenu
        arguments:
            - @knp_menu.factory
            - []
        tags:
            - { name: knp_menu.menu, alias: ihsan_simple_admin_main }