services:
    output_filter:
        class: Ihsan\Compressor\Bridge\Symfony\HtmlCompressorOutputFilter
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    css_filter:
        class: Ihsan\Compressor\Bridge\Symfony\AsseticCssFilter
        tags:
           - { name: assetic.filter, alias: css_compressor }

    ihsan.simple_admin.crud_annotation_reader:
        class: Ihsan\SimpleAdminBundle\EventListener\AnnotationListener
        arguments:
            - @annotation_reader
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }

    ihsan.simple_admin.user_controller_dependency_pass:
        class: Ihsan\SimpleAdminBundle\EventListener\UserControllerDependencyPassListener
        arguments:
            - @service_container
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }

    ihsan.simple_admin.twig_global_variable_pass:
        class: Ihsan\SimpleAdminBundle\EventListener\TwigGlobaVariablePassListener
        arguments:
            - @service_container
        tags:
            - { name: "kernel.event_listener", event: "kernel.request", method: "onKernelRequest" }