services:
    output_filter:
        class: Ihsan\Compressor\Bridge\Symfony\HtmlCompressorOutputFilter
        arguments:
            - @kernel
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    css_filter:
        class: Ihsan\Compressor\Bridge\Symfony\AsseticCssFilter
        tags:
           - { name: assetic.filter, alias: css_compressor }

    ihsan.simple_admin.annotation:
        class: Ihsan\SimpleAdminBundle\EventListener\AnnotationListener
        arguments:
            - @annotation_reader
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }

    ihsan.simple_admin.db_util:
        class: Ihsan\SimpleAdminBundle\EventListener\DbUtilListener
        arguments:
            - @kernel
            - @service_container
            - @doctrine.orm.entity_manager
        tags:
            - { name: "kernel.event_listener", event: "kernel.request", method: "onKernelRequest" }

    ihsan.simple_admin.delete_user:
        class: Ihsan\SimpleAdminBundle\EventListener\DeleteUserListener
        arguments:
            - @service_container
            - @security.token_storage
            - @translator
        tags:
            - { name: "kernel.event_listener", event: "ihsan.simple_admin.pre_delete_event", method: "onDeleteUser" }

    ihsan.simple_admin.controller_default_view_pass:
        class: Ihsan\SimpleAdminBundle\DependencyInjection\Compiler\OverrideControllerDefaultViewPass
        arguments:
            - @service_container
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }

    ihsan.simple_admin.user_controller_dependency_pass:
        class: Ihsan\SimpleAdminBundle\DependencyInjection\Compiler\UserControllerDependencyPass
        arguments:
            - @service_container
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }

    ihsan.simple_admin.index_controller_dependency_pass:
        class: Ihsan\SimpleAdminBundle\DependencyInjection\Compiler\IndexControllerDependencyPass
        arguments:
            - @service_container
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }

    ihsan.simple_admin.twig_global_variable_pass:
        class: Ihsan\SimpleAdminBundle\DependencyInjection\Compiler\TwigGlobaVariablePass
        arguments:
            - @service_container
        tags:
            - { name: "kernel.event_listener", event: "kernel.request", method: "onKernelRequest" }

    ihsan.simple_admin.menu:
        class: Ihsan\SimpleAdminBundle\Menu\Builder
        arguments:
            - @router
            - @service_container

    ihsan.simple_admin.main_menu:
        class: Knp\Menu\MenuItem
        factory_service: ihsan.simple_admin.menu
        factory_method: mainMenu
        arguments:
            - @knp_menu.factory
            - []
        tags:
            - { name: knp_menu.menu, alias: ihsan_simple_admin_main_menu }

    ihsan.simple_admin.change_password_form:
        class: Ihsan\SimpleAdminBundle\Form\ChangePasswordType
        arguments:
            - @service_container

    ihsan.simple_admin.user_form:
        class: Ihsan\SimpleAdminBundle\Form\UserType
        arguments:
            - @service_container
            - %security.role_hierarchy.roles%